server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-member
###redis配置
  redis:
    host: 47.100.112.202
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 3000
##日志打印
logging:
  level:
    com.bluetao.member.mapper: DEBUG

####swagger相关配置
swagger:
  base-package: com.bluetao.menber.service
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 我的微服务电商项目接口
  version: 1.1
#  contact:
#    name: 97后互联网架构师-余胜军
#    email: 644064779@qq.com
