server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-weixin
  ###redis配置
  redis:
    host: 47.100.112.202
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 3000
####swagger相关配置
swagger:
  base-package: com.bluetao.menber.service
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 我的微服务电商项目接口
  version: 1.1

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    configs:
      - appId: wx84eccc633d4595a4 #（一个公众号的appid）
        secret: a4e27dbbca45b35c6a0469bf933e95b2 #（公众号的appsecret）
        token: bluetao #（接口配置里的Token值）


