###服务启动端口号
server:
  port: 80
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: api-gateway
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


### 配置网关反向代理
zuul:
  routes:
    api-a:
      ### 以 /api-member/访问转发到会员服务
      path: /api-member/**
      serviceId: service-member
      #设置zuul屏蔽的敏感头（默认屏蔽Cookie）
  sensitive-headers: Set-Cookie,Authorization

